#! /bin/sh

# This should be executed in a clean working copy of the test repo.

set -e

BASE="$(dirname "$(cd $(dirname "$0") && pwd)")"
. "$BASE/t/test-lib.sh"

GIT_IMERGE="git-imerge"
TMP="$BASE/t/tmp/drop"
DESCRIPTION="git-imerge drop test repository"

rm -rf "$TMP"
mkdir -p "$TMP"
cd "$TMP"

git init
echo "$DESCRIPTION" >.git/description
git config user.name 'Loú User'
git config user.email 'luser@example.com'

modify a.txt 0
commit -m 'm⇒0'

for i in $(seq 6)
do
    modify a$i.txt $i
    commit -m "a$i⇒$i"
done

ln -s "$BASE/imerge.css" .

git checkout -b dropped master
"$GIT_IMERGE" drop HEAD~5..HEAD~3
"$GIT_IMERGE" diagram --commits --frontier --html=imerge-drop.html
"$GIT_IMERGE" finish

git checkout -b reverted master
"$GIT_IMERGE" revert HEAD~5..HEAD~3
"$GIT_IMERGE" diagram --commits --frontier --html=imerge-revert.html
"$GIT_IMERGE" finish

git --no-pager diff dropped reverted

